# Generated by Django 5.1.6 on 2025-02-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_expensecategory_transaction_is_recurring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.CharField(max_length=50, verbose_name='category'),
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='is_recurring',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='notes',
        ),
        migrations.DeleteModel(
            name='ExpenseCategory',
        ),
    ]
