# Generated by Django 5.1.6 on 2025-02-28 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_expensecategory_transaction_is_recurring_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensecategory',
            name='name_ar',
            field=models.CharField(default='', max_length=50, verbose_name='name (Arabic)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expensecategory',
            name='name_fr',
            field=models.CharField(default=' ', max_length=50, verbose_name='name (French)'),
            preserve_default=False,
        ),
    ]
